Fix logic typo in the JobPackageTracker
cur need to be non null or the system process crashes
with a stack signature like.

*** FATAL EXCEPTION IN SYSTEM PROCESS: main
java.lang.NullPointerException: Attempt to invoke virtual method 'lo\
ng com.android.server.job.JobPackageTracker$PackageEntry.getActiveTi\
me(long)' on a null object reference
at com.android.server.job.JobPackageTracker.getLoadFactor(JobPackage\
Tracker.java:398)
at com.android.server.job.JobSchedulerService.adjustJobPriority(JobS\
chedulerService.java:1285)
at com.android.server.job.JobSchedulerService.evaluateJobPriorityLoc\
ked(JobSchedulerService.java:1304)

the second test is now redundant as we bail out early if either
last or cur is null so it is removed.

Co-Author: Henrik Antonsson <henrik.antonsson@sonymobile.com>
Test: make run
Change-Id: Id395c2a3d8e46c00b4876738e7fd258a31808268